r2dbc:
  host: localhost
  port: 3306
  db: dev
  username: root
  password: 1234

logging:
  level:
    root: info
    org:
      springframework:
        r2dbc: info

file-name: /Users/mayard/Downloads/소상공인시장진흥공단_상가(상권)정보_20211231/소상공인시장진흥공단_상가(상권)정보_제주_202112.csv